const service1 = [
	{
		id: 1,
		router: '/',
		src: 'src/assets/icon/sideBar/信封.svg',
		text: '我的消息',
		if_more: false,
		more: '',
		if_line: true,
	},
	{
		id: 2,
		router: '/',
		src: 'src/assets/icon/sideBar/云贝.svg',
		text: '云贝中心',
		if_more: false,
		more: '',
		if_line: true,
	},
	{
		id: 3,
		router: '/',
		src: 'src/assets/icon/sideBar/灯泡.svg',
		text: '创作者中心',
		if_more: false,
		more: '',
		if_line: false,
	},
];

const service2 = [
	{
		id: 1,
		router: '/',
		src: 'src/assets/icon/sideBar/六芒星.svg',
		text: '趣测',
		if_more: true,
		more: '点击查看今日运势',
		if_line: false,
	},
	{
		id: 2,
		router: '/',
		src: 'src/assets/icon/sideBar/票.svg',
		text: '云村有票',
		if_more: false,
		more: '',
		if_line: false,
	},
	{
		id: 3,
		router: '/',
		src: 'src/assets/icon/sideBar/问号.svg',
		text: '多多西西口袋',
		if_more: false,
		more: '',
		if_line: false,
	},
	{
		id: 4,
		router: '/',
		src: 'src/assets/icon/sideBar/商城.svg',
		text: '商城',
		if_more: false,
		more: '',
		if_line: false,
	},
	{
		id: 5,
		router: '/',
		src: 'src/assets/icon/sideBar/beat.svg',
		text: 'Beat专区',
		if_more: true,
		more: '投稿赢万元好礼!',
		if_line: false,
	},
	{
		id: 6,
		router: '/',
		src: 'src/assets/icon/sideBar/彩铃.svg',
		text: '口袋彩铃',
		if_more: false,
		more: '',
		if_line: false,
	},
	{
		id: 7,
		router: '/',
		src: 'src/assets/icon/sideBar/游戏中心.svg',
		text: '游戏专区',
		if_more: true,
		more: '音乐浇灌治愈花园',
		if_line: false,
	},
];

const service3 = [
	{
		id: 1,
		router: '/',
		src: 'src/assets/icon/sideBar/设置.svg',
		text: '设置',
		if_more: false,
		more: '',
		if_line: false,
	},
	{
		id: 2,
		router: '/',
		src: 'src/assets/icon/sideBar/深色模式.svg',
		text: '深色模式',
		if_more: true,
		more: '关闭',
		if_line: false,
	},
	{
		id: 3,
		router: '/',
		src: 'src/assets/icon/sideBar/定时.svg',
		text: '定时关闭',
		if_more: false,
		more: '',
		if_line: false,
	},
	{
		id: 4,
		router: '/',
		src: 'src/assets/icon/sideBar/个性装扮.svg',
		text: '个性装扮',
		if_more: false,
		more: '',
		if_line: false,
	},
	{
		id: 5,
		router: '/',
		src: 'src/assets/icon/sideBar/边听边存.svg',
		text: '边听边存',
		if_more: true,
		more: '未开启',
		if_line: false,
	},
	{
		id: 6,
		router: '/',
		src: 'src/assets/icon/sideBar/免流量.svg',
		text: '在线听歌免流量',
		if_more: false,
		more: '',
		if_line: false,
	},
	{
		id: 7,
		router: '/',
		src: 'src/assets/icon/sideBar/黑名单.svg',
		text: '音乐黑名单',
		if_more: false,
		more: '',
		if_line: false,
	},
	{
		id: 8,
		router: '/',
		src: 'src/assets/icon/sideBar/盾牌.svg',
		text: '青少年模式',
		if_more: true,
		more: '未开启',
		if_line: false,
	},
	{
		id: 9,
		router: '/',
		src: 'src/assets/icon/sideBar/闹钟.svg',
		text: '音乐闹钟',
		if_more: false,
		more: '',
		if_line: false,
	},
];

const service4 = [
	{
		id: 1,
		router: '/',
		src: 'src/assets/icon/sideBar/订单.svg',
		text: '我的订单',
		if_more: false,
		more: '',
		if_line: false,
	},
	{
		id: 2,
		router: '/',
		src: 'src/assets/icon/sideBar/票.svg',
		text: '优惠券',
		if_more: false,
		more: '',
		if_line: false,
	},
	{
		id: 3,
		router: '/',
		src: 'src/assets/icon/sideBar/客服.svg',
		text: '我的客服',
		if_more: false,
		more: '',
		if_line: false,
	},
	{
		id: 4,
		router: '/',
		src: 'src/assets/icon/sideBar/分享.svg',
		text: '分享网易云音乐',
		if_more: false,
		more: '',
		if_line: false,
	},
	{
		id: 5,
		router: '/',
		src: 'src/assets/icon/sideBar/信息收集.svg',
		text: '个人信息收集与使用清单',
		if_more: false,
		more: '',
		if_line: false,
	},
	{
		id: 6,
		router: '/',
		src: 'src/assets/icon/sideBar/第三方.svg',
		text: '个人信息第三方共享清单',
		if_more: false,
		more: '',
		if_line: false,
	},
	{
		id: 7,
		router: '/',
		src: 'src/assets/icon/sideBar/隐私.svg',
		text: '个人信息与隐私保护',
		if_more: false,
		more: '',
		if_line: false,
	},
	{
		id: 8,
		router: '/',
		src: 'src/assets/icon/sideBar/关于.svg',
		text: '关于',
		if_more: false,
		more: '',
		if_line: false,
	},
];

export { service1, service2, service3, service4 };
